import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ← Change to Inter
import "./globals.css";

// Change from Sora to Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // ← Change variable name
  display: "swap",
});

export const metadata: Metadata = {
  title: "ShipCode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={inter.variable}
        style={{ margin: 0, background: "#050608" }}
      >
        {children}
      </body>
    </html>
  );
}
