# setup-phase4-port8080.ps1 - Using only port 8080 with host-gateway

Write-Host "`n🚀 ShipStack Phase 4 - Nginx Setup" -ForegroundColor Cyan
Write-Host "====================================`n"

# Add Docker to PATH if needed
$dockerPath = "C:\Program Files\Docker\Docker\resources\bin"
if (Test-Path "$dockerPath\docker.exe") {
    $env:Path = "$dockerPath;$env:Path"
    Write-Host "✅ Docker path configured" -ForegroundColor Green
}

# Verify Docker
$dockerVersion = docker --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Docker not found!" -ForegroundColor Red
    exit 1
}
Write-Host "✅ $dockerVersion"

# Create nginx config directory
$nginxDir = "C:\shipstack\nginx"
if (-not (Test-Path $nginxDir)) {
    New-Item -ItemType Directory -Path $nginxDir -Force | Out-Null
    Write-Host "✅ Created $nginxDir"
} else {
    Write-Host "✅ $nginxDir already exists"
}

# Write nginx config - WITHOUT BOM
$confPath = Join-Path $nginxDir "shipstack.conf"
$configContent = @"
# Auto-generated by ShipStack
server {
    listen 80 default_server;
    server_name _;
    return 404 'ShipStack: no deployments yet';
    add_header Content-Type text/plain;
}
"@

# Remove BOM by using UTF8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($confPath, $configContent, $utf8NoBom)
Write-Host "✅ Wrote nginx config (UTF8 without BOM)"

# Write empty routes registry - also without BOM
$registryPath = Join-Path $nginxDir "routes.json"
[System.IO.File]::WriteAllText($registryPath, "[]", $utf8NoBom)
Write-Host "✅ Wrote route registry"

# Remove existing container
$existing = docker ps -a --filter "name=shipstack-nginx" --format "{{.Names}}" 2>$null
if ($existing -eq "shipstack-nginx") {
    Write-Host "🔄 Removing existing container..."
    docker rm -f shipstack-nginx | Out-Null
    Start-Sleep -Seconds 2
}

# Start nginx container on port 8080 with host-gateway
Write-Host "`n🐳 Starting nginx container on port 8080..." -ForegroundColor Yellow

docker run -d `
    --name shipstack-nginx `
    --restart unless-stopped `
    --add-host=host-gateway:host-gateway `
    -p 8080:80 `
    -v "${nginxDir}:/etc/nginx/conf.d" `
    nginx:1.25-alpine `
    sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Failed to start nginx on port 8080!" -ForegroundColor Red
    exit 1
}

$nginxPort = 8080
Start-Sleep -Seconds 3

# Verify container is running
$running = docker ps --filter "name=shipstack-nginx" --format "{{.Names}}"
if ($running -eq "shipstack-nginx") {
    Write-Host "✅ nginx started successfully on port $nginxPort with host-gateway!" -ForegroundColor Green
    
    # Show container logs
    Write-Host "`n📋 Container logs:" -ForegroundColor Cyan
    docker logs shipstack-nginx --tail 5
    
    # Test the endpoint
    Start-Sleep -Seconds 2
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:$nginxPort" -UseBasicParsing -ErrorAction SilentlyContinue
        Write-Host "`n✅ Response: HTTP $($response.StatusCode)" -ForegroundColor Green
        Write-Host "✅ nginx is working correctly!" -ForegroundColor Green
    } catch {
        if ($_.Exception.Message -like "*404*") {
            Write-Host "`n✅ Got 404 response (expected - no deployments yet)" -ForegroundColor Green
            Write-Host "✅ nginx is working correctly!" -ForegroundColor Green
        } else {
            Write-Host "`n⚠️  Response: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
} else {
    Write-Host "❌ Container failed to start" -ForegroundColor Red
    docker logs shipstack-nginx
    exit 1
}

Write-Host "`n📋 Add to your backend .env file:" -ForegroundColor Yellow
Write-Host "   NGINX_CONFIG_DIR=C:\shipstack\nginx"
Write-Host "   NGINX_CONTAINER=shipstack-nginx"
Write-Host "   NGINX_PUBLIC_PORT=8080"

Write-Host "`n✅ Phase 4 setup complete!" -ForegroundColor Green
Write-Host "   Your projects will be available at: http://<project-name>.localhost:8080"
Write-Host ""