/**
 * nginx.service.ts
 *
 * Manages the Nginx reverse-proxy configuration for ShipStack.
 *
 * Responsibilities:
 *  - Write / update the nginx upstream map on disk
 *  - Signal the nginx Docker container to reload (docker exec nginx nginx -s reload)
 *  - Derive a URL-safe subdomain from a project name
 *
 * Design constraints (Windows + Docker Desktop):
 *  - All file I/O uses path.join() — no hard-coded POSIX paths
 *  - nginx runs as a Docker container named "shipstack-nginx"
 *  - The config volume is mounted at NGINX_CONFIG_DIR (env var, default: C:\shipstack\nginx)
 *  - reload uses `docker exec` so we don't need the nginx binary on the host
 */

import fs from "fs/promises";
import path from "path";
import { execSync } from "child_process";

// ─── Config ───────────────────────────────────────────────────────────────────

/** Directory on the HOST that is bind-mounted into the nginx container. */
const NGINX_CONFIG_DIR = process.env.NGINX_CONFIG_DIR ?? "C:\\shipstack\\nginx";

/** Name of the running nginx Docker container. */
const NGINX_CONTAINER = process.env.NGINX_CONTAINER ?? "shipstack-nginx";

/** Path inside the container that corresponds to NGINX_CONFIG_DIR. */
const CONTAINER_CONF_DIR = "/etc/nginx/conf.d";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface RouteEntry {
  subdomain: string;
  hostPort: number;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Convert a project name to a URL-safe subdomain.
 * e.g. "My Portfolio App!" → "my-portfolio-app"
 */
export function toSubdomain(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-") // non-alphanum → dash
    .replace(/^-+|-+$/g, "") // trim leading/trailing dashes
    .slice(0, 63); // DNS label max length
}

/**
 * Build the public URL for a subdomain.
 * Uses NGINX_PUBLIC_PORT env (default 80) so the URL is always clean.
 */
export function buildPublicUrl(subdomain: string): string {
  const port = process.env.NGINX_PUBLIC_PORT ?? "80";
  const portSuffix = port === "80" ? "" : `:${port}`;
  return `http://${subdomain}.localhost${portSuffix}`;
}

// ─── Config generation ────────────────────────────────────────────────────────

/**
 * Generate the full nginx.conf content from the current route table.
 *
 * Strategy: one `server` block per subdomain. Each block matches on
 * `server_name <subdomain>.localhost` and proxies to `127.0.0.1:<hostPort>`.
 *
 * We proxy to 127.0.0.1 (not localhost) because on Windows Docker Desktop,
 * `localhost` may resolve to ::1 (IPv6) which Docker does not bind.
 */
function buildNginxConf(routes: RouteEntry[]): string {
  const serverBlocks = routes
    .map(
      ({ subdomain, hostPort }) => `
  # ── ${subdomain} ──────────────────────────────────────────────
  server {
    listen 80;
    server_name ${subdomain}.localhost;

    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Standard proxy headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Timeouts (generous for SPA initial load)
    proxy_connect_timeout 10s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;

    location / {
        proxy_pass http://host-gateway:${hostPort};
    }
  }`,
    )
    .join("\n");

  // Default catch-all → 404
  const catchAll = `
  # ── catch-all ────────────────────────────────────────────────
  server {
    listen 80 default_server;
    server_name _;
    return 404 "ShipStack: subdomain not found\\n";
    add_header Content-Type text/plain;
  }`;

  return `# Auto-generated by ShipStack nginx.service.ts — DO NOT EDIT MANUALLY
# Regenerated on every deployment start/stop.
${serverBlocks}
${catchAll}
`;
}

// ─── Registry file ────────────────────────────────────────────────────────────

const REGISTRY_FILE = path.join(NGINX_CONFIG_DIR, "routes.json");

/** Load the persisted route registry from disk. Returns [] on first run. */
async function loadRegistry(): Promise<RouteEntry[]> {
  try {
    const raw = await fs.readFile(REGISTRY_FILE, "utf-8");
    return JSON.parse(raw) as RouteEntry[];
  } catch {
    return [];
  }
}

/** Persist the route registry to disk. */
async function saveRegistry(routes: RouteEntry[]): Promise<void> {
  await fs.mkdir(NGINX_CONFIG_DIR, { recursive: true });
  await fs.writeFile(REGISTRY_FILE, JSON.stringify(routes, null, 2), "utf-8");
}

// ─── Nginx reload ─────────────────────────────────────────────────────────────

/**
 * Write the generated conf to disk and ask nginx to reload its config.
 * Uses `docker exec` so the host doesn't need nginx installed.
 */
async function applyAndReload(routes: RouteEntry[]): Promise<void> {
  const conf = buildNginxConf(routes);
  const confPath = path.join(NGINX_CONFIG_DIR, "shipstack.conf");

  await fs.mkdir(NGINX_CONFIG_DIR, { recursive: true });
  await fs.writeFile(confPath, conf, "utf-8");

  console.log(`[nginx.service] Config written → ${confPath}`);
  console.log(`[nginx.service] Active routes: ${routes.length}`);

  // Test config first, then reload
  try {
    execSync(`docker exec ${NGINX_CONTAINER} nginx -t`, {
      timeout: 10_000,
      stdio: "pipe",
    });
    execSync(`docker exec ${NGINX_CONTAINER} nginx -s reload`, {
      timeout: 10_000,
      stdio: "pipe",
    });
    console.log(`[nginx.service] ✅ Nginx reloaded successfully`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // Don't throw — a reload failure should not crash the deployment worker.
    // The container might not be running yet (first boot), which is fine.
    console.warn(`[nginx.service] ⚠️ Nginx reload warning: ${msg}`);
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Register a new subdomain → port mapping and reload nginx.
 * Called by the deployment worker after a container is healthy.
 */
export async function registerRoute(entry: RouteEntry): Promise<void> {
  const routes = await loadRegistry();

  // Remove any stale entry for this subdomain (re-deploy scenario)
  const filtered = routes.filter((r) => r.subdomain !== entry.subdomain);
  filtered.push(entry);

  await saveRegistry(filtered);
  await applyAndReload(filtered);
}

/**
 * Remove a subdomain mapping and reload nginx.
 * Called when a deployment is stopped or deleted.
 */
export async function unregisterRoute(subdomain: string): Promise<void> {
  const routes = await loadRegistry();
  const filtered = routes.filter((r) => r.subdomain !== subdomain);

  if (filtered.length === routes.length) {
    // Nothing changed — skip disk write and reload
    return;
  }

  await saveRegistry(filtered);
  await applyAndReload(filtered);
}

/**
 * Return all currently registered routes (read-only snapshot).
 */
export async function listRoutes(): Promise<RouteEntry[]> {
  return loadRegistry();
}

/**
 * Rebuild and reload nginx from the persisted registry.
 * Useful on server startup to restore routes after a restart.
 */
export async function bootstrapNginx(): Promise<void> {
  const routes = await loadRegistry();
  console.log(
    `[nginx.service] Bootstrapping nginx with ${routes.length} route(s)`,
  );
  await applyAndReload(routes);
}
